Common:
  Version: string
  Health: string

RestServer:
  Host: string
  Port: itn

GRPCServer:
  Port: int

PostgreSQL:
  Db: string
  Host: string #host.docker.internal
  Port: int
  User: string
  Password: string
  SSLMode: string
  MaxOpenConnections:    int
  MaxIdleConnections:    int
  ConnectionMaxLifetime: time.Duration
  ConnectionMaxIdletime: time.Duration

Jwt:
  Salt: string
  Issuer: string
  Subject: string
  Audience:
    - string
  ExpiresIn: time.Duration

Logger:
  Level: string
  Colors: bool
  FullTimestamp: bool